apiVersion: v1
kind: Service
metadata:
  name: peer1-org1-example-com ####name of Service, unique
spec:
  type: NodePort ####can be accessed from outside
  ports:
  - port: 30051 ####port of service, open to pub
    nodePort: 30051
  selector:
    app: peer0-org1 ####label for Pod
