PeerOrgs:
  - Name: Yong
    Domain: yong.thinking.com
    EnableNodeOUs: true
    #这个组织有两个peer节点，这个组织有两个用户和一个Admin用户
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: Ben
    Domain: ben.thinking.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: Guo
    Domain: guo.thinking.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2