apiVersion: v1
kind: ReplicationController ####type of RC
metadata:
  name: test-pvc ####name of RC, unique
spec:
  replicas: 1 ####Num of copy for Pod
  selector:
    app: test-pvc ####expected label for Pod
  template: ####Pod instance
    metadata:
      labels:
         app: test-pvc ####label for Pod copy
    spec:
      containers: ####def of container in Pod
        - name: test-pvc ####container name
          image: ubuntu ####container img
          imagePullPolicy: IfNotPresent
          tty: true ####To keep the container active, you must exec at least one continuously running task or set tty=true
          volumeMounts:
            - mountPath: "/fabric-config/"
              name: fabric-config
      volumes:
        - name: fabric-config
          persistentVolumeClaim:
            claimName: pvc-fabric