version: '2'

networks:
  thinking:

services:
  kafka.thinking.com:
    image: ubuntu
    container_name: kafka.thinking.com
    command: sh /cmd/kafka-sig.sh
    tty: true
    networks:
    - thinking
    volumes:
    - /etc/java-8-openjdk:/etc/java-8-openjdk
    - /usr/lib/jvm/java-8-openjdk-amd64:/usr/lib/jvm/java-8-openjdk-amd64
    - $PWD/kafka-sig-cmd:/cmd
    - /home/yong/Desktop/kafka_2.11-1.1.1:/usr/local/kafka
    environment:
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
    - PATH=${PATH}:/usr/lib/jvm/java-8-openjdk-amd64/bin:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin
