apiVersion: v1
kind: Service
metadata:
  name: peer1-org1-example-com ####name of Service, unique
spec:
  type: NodePort ####can be accessed from outside
  ports:
  - port: 8051 ####port of service, open to pub
  selector:
    app: peer1-org1 ####label for Pod
