apiVersion: v1
kind: ReplicationController ####type of RC
metadata:
  name: peer1-org1 ####name of RC, unique
spec:
  replicas: 1 ####Num of copy for Pod
  selector:
    app: peer1-org1 ####expected label for Pod
  template: ####Pod instance
    metadata:
      labels:
         app: peer1-org1 ####label for Pod copy
    spec:
      containers: ####def of container in Pod
        - name: peer1-org1 ####container name
          image: hyperledger/fabric-peer ####container img
          env:
            - name: CORE_PEER_ID
              value: peer1.org1.example.com
            - name: CORE_PEER_ADDRESS
              value: peer1-org1-example-com:8051
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:8051
            - name: CORE_PEER_CHAINCODEADDRESS
              value: peer1-org1-example-com:8052
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 0.0.0.0:8052
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0-org1-example-com:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer1-org1-example-com:8051
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_VM_ENDPOINT
              value: unix:///host/var/run/docker.sock
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: CORE_PEER_TLS_ENABLED
              value: 'false'
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: 'true'
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: 'false'
            - name: CORE_PEER_PROFILE_ENABLED
              value: 'true'
            - name: CORE_PEER_TLS_CERT_FILE
              value: /fabric-config/fabric-samples/first-network/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /fabric-config/fabric-samples/first-network/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /fabric-config/fabric-samples/first-network/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          imagePullPolicy: IfNotPresent
          #command: ["peer node start"]
          tty: true
          ports:
            - containerPort: 8051
          volumeMounts:
            - mountPath: "/fabric-config/"
              name: fabric-config
      volumes:
        - name: fabric-config
          persistentVolumeClaim:
            claimName: pvc-fabric