!sys_channel.ProfileConfig
Profiles: 
   SystemChannelConfig: 
      Capabilities: 
         V1_1: true
         V1_3: true
         V1_4_3: true
      Consortiums: 
         SampleConsortium: 
            Organizations: 
            - !sys_channel.ProfileConfig$PeerOrgConfig
               AnchorPeers: 
               - !sys_channel.ProfileConfig$AnchorConfig
                  Host: peer0.org1.example.com
                  Port: 7051
               ID: Org1MSP
               MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
               Name: Org1MSP
               Policies: 
                  Admins: 
                     Rule: "OR('Org1MSP.admin')"
                     Type: Signature
                  Readers: 
                     Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
                     Type: Signature
                  Writers: 
                     Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
                     Type: Signature
            - !sys_channel.ProfileConfig$PeerOrgConfig
               AnchorPeers: 
               - !sys_channel.ProfileConfig$AnchorConfig
                  Host: peer0.org2.example.com
                  Port: 9051
               ID: Org2MSP
               MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
               Name: Org2MSP
               Policies: 
                  Admins: 
                     Rule: "OR('Org2MSP.admin')"
                     Type: Signature
                  Readers: 
                     Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
                     Type: Signature
                  Writers: 
                     Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
                     Type: Signature
            - !sys_channel.ProfileConfig$PeerOrgConfig
               AnchorPeers: 
               - !sys_channel.ProfileConfig$AnchorConfig
                  Host: peer0.org3.example.com
                  Port: 11051
               ID: Org3MSP
               MSPDir: crypto-config/peerOrganizations/org3.example.com/msp
               Name: Org3MSP
               Policies: 
                  Admins: 
                     Rule: "OR('Org3MSP.admin')"
                     Type: Signature
                  Readers: 
                     Rule: "OR('Org3MSP.admin', 'Org3MSP.peer', 'Org3MSP.client')"
                     Type: Signature
                  Writers: 
                     Rule: "OR('Org3MSP.admin', 'Org3MSP.client')"
                     Type: Signature
      Orderer: 
         Addresses: 
         - orderer.example.com:7050
         BatchSize: 
            AbsoluteMaxBytes: 99 MB
            MaxMessageCount: 10
            PreferredMaxBytes: 512 KB
         BatchTimeout: 2s
         Capabilities: 
            V1_1: true
            V1_4_2: true
         OrdererType: solo
         Organizations: 
         - !sys_channel.ProfileConfig$OrdererOrgConfig
            ID: OrdererMSP
            MSPDir: crypto-config/ordererOrganizations/example.com/msp
            Name: OrdererOrg
            Policies: 
               Admins: 
                  Rule: "OR('OrdererMSP.admin')"
                  Type: Signature
               Readers: 
                  Rule: "OR('OrdererMSP.member')"
                  Type: Signature
               Writers: 
                  Rule: "OR('OrdererMSP.member')"
                  Type: Signature
         Policies: 
            Admins: 
               Rule: "MAJORITY Admins"
               Type: ImplicitMeta
            BlockValidation: 
               Rule: "ANY Writers"
               Type: ImplicitMeta
            Readers: 
               Rule: "ANY Readers"
               Type: ImplicitMeta
            Writers: 
               Rule: "ANY Writers"
               Type: ImplicitMeta
      Policies: 
         Admins: 
            Rule: "MAJORITY Admins"
            Type: ImplicitMeta
         Readers: 
            Rule: "ANY Readers"
            Type: ImplicitMeta
         Writers: 
            Rule: "ANY Writers"
            Type: ImplicitMeta
