NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.ben.thinking.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.ben.thinking.com-cert.pem
    OrganizationalUnitIdentifier: peer
