name: "fuck-my_test"
description: "fuck-you"
version: 1.0.0
 
client:
  organization: yong.thinking.com
  logging:
    level: info
  cryptoconfig:
    path: /mnt/hgfs/3-orgs-test/network/crypto-config
  credentialStore:
    path: /tmp/
    cryptoStore:
      path: /tmp/msp
  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     level: 256
  tlsCerts:
    systemCertPool: true
    client:
      key:
        path: /mnt/hgfs/3-orgs-test/network/crypto-config/peerOrganizations/yong.thinking.com/users/Admin@yong.thinking.com/tls/client.key
      cert:
        path: /mnt/hgfs/3-orgs-test/network/crypto-config/peerOrganizations/yong.thinking.com/users/Admin@yong.thinking.com/tls/client.crt
        
channels:
  mythnkingchannel:
    peers:
      peer0.yong.thinking.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
          
organizations:
  yong.thinking.com:
    mspid: YongPeerMSP
    cryptoPath: /mnt/hgfs/3-orgs-test/network/crypto-config/peerOrganizations/yong.thinking.com/users/Admin@yong.thinking.com/msp
    peers:
      - peer0.yong.thinking.com
      
orderers:
  thinking_orderer_host.thinking.com:
    #url: thinking_orderer_host.thinking.com:7050
    url: localhost:7050
    grpcOptions:
      ssl-target-name-override: thinking_orderer_host.thinking.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /mnt/hgfs/3-orgs-test/network/crypto-config/ordererOrganizations/thinking.com/tlsca/tlsca.thinking.com-cert.pem
 
peers:
  peer0.yong.thinking.com:
    #url: peer0.yong.thinking.com:7051
    url: localhost:7051
    #eventUrl: peer0.yong.thinking.com:7053
    eventUrl: localhost:7053
    grpcOptions:
      ssl-target-name-override: peer0.yong.thinking.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /mnt/hgfs/3-orgs-test/network/crypto-config/peerOrganizations/yong.thinking.com/peers/peer0.yong.thinking.com/tls/ca.crt
 
entityMatchers:
  orderer:
    - pattern: (\w*)thinking_orderer_host.thinking.com(\w*)
      #urlSubstitutionExp: thinking_orderer_host.thinking.com:7050
      urlSubstitutionExp: localhost:7050
      sslTargetOverrideUrlSubstitutionExp: thinking_orderer_host.thinking.com
      mappedHost: thinking_orderer_host.thinking.com
