!OrdererOrgConfigSet
OrdererOrgs: 
- !Config
   Domain: example.com
   EnableNodeOUs: true
   Name: Orderer
   Specs: 
   - !HostConfig
      Hostname: orderer
   - !HostConfig
      Hostname: orderer2
   - !HostConfig
      Hostname: orderer3
   - !HostConfig
      Hostname: orderer4
   - !HostConfig
      Hostname: orderer5
