version: '2'

volumes:
  peer1.org2.example.com:

networks:
  thinking:

services:
  peer1.org2.example.com:
    image: hyperledger/fabric-peer
    container_name: peer1.org2.example.com
    environment:
      - CORE_PEER_ID=peer1.org2.example.com
      - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-ca-log_thinking
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - $PWD/client-guo-msps/org2.example.com/peer1/msp:/etc/hyperledger/fabric/msp
        - $PWD/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - peer1.org2.example.com:/var/hyperledger/production
    command: /bin/bash
    ports:
      - 10051:7051
      - 10053:7053
    networks:
      - thinking
    tty: true
