apiVersion: v1
kind: PersistentVolume
metadata:
  name: crypto-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/yong/nfs-test/fabric-samples/first-network/crypto-config
    server: 192.168.186.151