apiVersion: v1
kind: PersistentVolume
metadata:
  name: genesis
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/yong/nfs-test/fabric-samples/first-network/channel-artifacts/genesis.block
    server: 192.168.186.151
