apiVersion: v1
kind: PersistentVolume
metadata:
  name: orderer-msp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/yong/nfs-test/fabric-samples/first-network/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp
    server: 192.168.186.151