apiVersion: v1
kind: PersistentVolume
metadata:
  name: peer1-msp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/yong/nfs-test/fabric-samples/first-network/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp
    server: 192.168.186.151
