apiVersion: v1
kind: PersistentVolume
metadata:
  name: peer0-tls
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/yong/nfs-test/fabric-samples/first-network/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls
    server: 192.168.186.151