apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fabric
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/yong/nfs-test
    server: 192.168.186.151
