apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peer-msp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


kind: PersistentVolumeClaim
metadata:
  name: peer-tls
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
      
kind: PersistentVolumeClaim
metadata:
  name: chain-code
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


kind: PersistentVolumeClaim
metadata:
  name: crypto-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
      
kind: PersistentVolumeClaim
metadata:
  name: channel-artifacts
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi